version: '3.7'
services:
    php-apache:
        image: php:8.1.3-apache
        ports:
            - "8080:80"
            - "8000:8000"
        volumes:
            - ./:/var/www
            - ./public:/var/www/public